### ISSUE TITLE
Make dCFE

### ISSUE THREAD

**Issue by taddyb** [NWC-CUAHSI-Summer-Institute/cfe_py#7]
This is to track the progress of making CFE differentiable

**Comment by taddyb** [comment]
See PR: https://github.com/NWC-CUAHSI-Summer-Institute/dCFE/pull/1 for the template creation and documentation

NOTE: We are making a fork of cfe_py as to not interrupt the structure of `cfe_py`

**Comment by RY4GIT** [comment]
Ryoko Todo
- [ ] Edit data class, x = (basin, time, forcing/attr), c = (basin, forcing/attr) 
- [ ] Edit models, cfe under src/physics, edit dCFE init, forward
- [ ] ODE-torch


Refer to https://github.com/NWC-CUAHSI-Summer-Institute/dpLGAR

**Comment by RY4GIT** [comment]
Completed with this

https://github.com/NWC-CUAHSI-Summer-Institute/dCFE/pull/4
